[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket  = { version = "0.5.1", features = ["json"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"